#+title: Prevent software (adapted for Lazarus)
#+author: Original by Jan Barendregt (converted to Lazarus by Mark Clements)

* Introduction

- Prevent is a GUI application to calculate the incidence and mortality following a risk factor intervention. The software calculates population impact fractions and time impact fractions. 
- The methods and software are described in the PhD thesis by Louise Gunning Schepers: https://repub.eur.nl/pub/51053/881123_GUNNING-SCHEPERS-Louisa-Johanna.pdf. 
- The Prevent software was developed by Jan Barendragt, who passed away on 3 June 2017. As per his last will and testament, this software has been released under GPL version 3.
- The original software was implemented in [[https://en.wikipedia.org/wiki/Delphi_(software)][Delphi]]. This version is a conversion to Free Pascal using the [[https://en.wikipedia.org/wiki/Lazarus_(software)][Lazarus IDE and libraries]].
- There is a [[https://github.com/mclements/prevent/blob/main/Prevent%20manual%2007.pdf][manual]] for the Prevent software as written in Delphi.  
- *The Lazarus conversion is a work in progress.*

* Issues with the Lazarus conversion
- [ ] There are two versions for ~Tgenentity.pzaanpas~ -- one using a cohort perspective and one using an age-group perspective. See [[disunit.pas]].

* Notes on the conversion to Lazarus
- Lazarus provides some support for converting applications from Delphi to Lazarus.
- Aside from the automatic conversions, the main structural change was to replace the ~.mdb~ Access database inputs with ~.db~ SQLite database inputs.
- As a minor technical issue, the ~datamodule2.inputq1~ instance of the ~TSQLQuery~ object requires the ~packetsize~ property to be ~-1~ -- otherwise it defaults to only reads the first ten rows of a query:).
- We provide some R functions that uses [[https://github.com/mdbtools/mdbtools][mdb-tools]] and [[https://sqlite.org/][sqlite3]] utilities to convert the ~.mdb~ database files to ~.db~ database files.

** Bug fixes
- Multiple memory issues on Ubuntu 24.04 and gtk were resolved by moving to qt5.
